### ISSUE TITLE
Compilation failure with gcc 6

### ISSUE THREAD

**Issue by SnarkBoojum** [JohnCremona/eclib#12]
This version isn't out yet, but some people already use it ; I got the following report on the Debian package:
>  timer.cc: In destructor 'timer::~timer()':
>  timer.cc:77:13: error: no match for 'operator!=' (operand types are
> 'std::ofstream {aka std::basic_ofstream<char>}' and 'long int')
>   if( file_ != NULL ) {

**Comment by jamesjer** [comment]
GCC 6 defaults to -std=gnu++14 instead of -std=gnu++98, which is the source of the problem.  The following patch should make the code compile with all 3 of C++98, C++11, and C++14.  Note that it also fixes a bug en passant; the code in timer::stream() currently sets s_ to &cout if the file cannot be opened, then overwrites s_ with &file_ anyway.

`--- libsrc/newforms.cc.orig	2016-01-02 09:25:01.000000000 -0700
+++ libsrc/newforms.cc	2016-02-04 20:45:31.427990171 -0700
@@ -1336,7 +1336,7 @@ void newforms::createfromolddata()
   ifstream intdatafile(intdataname.str().c_str());
   if(!intdatafile.is_open())
     {
-      cout<<"Unable to open data file "<<intdataname<<" for data input"<<endl;
+      cout<<"Unable to open data file "<<intdataname.str()<<" for data input"<<endl;
       abort();
       return;
     }
--- libsrc/timer.cc.orig	2016-01-02 09:25:01.000000000 -0700
+++ libsrc/timer.cc	2016-02-04 20:20:25.274119806 -0700
@@ -74,7 +74,7 @@ timer::~timer() {
   // Close file, if ever opened
   // Do not reference s_ _ever_. We do not
   // want to close std::cout nonetheless.
-  if( file_ != NULL ) {
+  if( file_.is_open() ) {
     file_.close();
   }
 }
@@ -101,15 +101,13 @@ void timer::stream( string filename ) {
     file_.open(filename.c_str(),ios::out|ios::trunc);
     
     // Check is file successfully opened
-    if( file_ == NULL ) {
-      {
-        cout << "File " << filename << " could not be opened ... using stout" << endl;
-        s_ = &cout;
-      }
+    if( !file_.is_open() ) {
+      cout << "File " << filename << " could not be opened ... using stout" << endl;
+      s_ = &cout;
+    } else {
+      // Point main reference to newly opened file
+      s_ = &file_;
     }
-
-    // Point main reference to newly opened file
-    s_ = &file_;
   }
 }
 
`

**Comment by jamesjer** [comment]
Well, so much for pasting in a patch.  I'll try submitting a pull request instead....

**Comment by JohnCremona** [comment]
Thanks
