### ISSUE TITLE
build failure with -std=c++17 and pari

### ISSUE THREAD

**Issue by isuruf** [JohnCremona/eclib#45]
`paridecl.h` has `long    rank(GEN x);`, but there's also `std::rank` in C++11.

When 
```
#include <string>
using namespace std;
```
is done in `libsrc/eclib/parifact.h`, `std::rank` is pulled in to the namespace with gcc 7.3. (doesn't happen with gcc 4.9)

This leads to a build failure, 

```
<PREFIX>/include/pari/paridecl.h:1442:19: error: return type specified for deduction guide
 long    rank(GEN x);
                   ^
<PREFIX>/include/pari/paridecl.h:1442:1: error: decl-specifier in declaration of deduction guide
 long    rank(GEN x);
 ^~~~
<PREFIX>/include/pari/paridecl.h:1442:19: error: 'long' or 'short' invalid for '__dguide_rank'
 long    rank(GEN x);
                   ^
<PREFIX>/include/pari/paridecl.h:1442:9: error: deduction guide for 'std::rank< <template-parameter-1-1> >' must have trailing return type
 long    rank(GEN x);
```

cc @saraedum

**Comment by saraedum** [comment]
Setting `-std=c++17` gives me the original error.

**Comment by isuruf** [comment]
This error might go away if we stopped doing `using namespace std`, but that's a lot of code to change.

**Comment by saraedum** [comment]
I'm not a C++ expert but I think this is the way this type of problem is handled usually. Of course, we could also force an older C++ standard but I guess that's not such a great idea in the long run.

**Comment by isuruf** [comment]
It might not be enough. Ran into this in lcalc as well.

**Comment by isuruf** [comment]
It is enough.

Following produces an error
```C++
#include <string.h>
using namespace std;

#include <pari/pari.h>
int main() {

}
```

Following doesn't
```C++
#include <string.h>

#include <pari/pari.h>
int main() {

}
```

**Comment by JohnCremona** [comment]
I have never wanted to not have a global std namespace sine it seemed ridiculous to have to write std::cout instead of cout for every output line -- and many more.  I also do not relish the prospect of changing almost every line of code for such a trivial reason.

Instead:  since almost no symbols from libpari are used, would it be possible to wrap the header file which include pari.h into a different namespace called pari?  Then I would not mind inserting pari:: in a few places.

**Comment by isuruf** [comment]
@JohnCremona, how about doing `using std::cout;` and whatever eclib need in a central place? Then you can use `cout` in other places. This prevents `std::rank` getting pulled in as `rank`.

**Comment by isuruf** [comment]
> Instead: since almost no symbols from libpari are used, would it be possible to wrap the header file which include pari.h into a different namespace called pari? 

This is not possible since pari is including standard headers and they'll be pulled in to the pari namespace and cause issues.

**Comment by JohnCremona** [comment]
I spent hours, perhaps days, on reorganising the header files earlier this year.  I am not going to spend more time on that now, as I have more important things to do.

**Comment by JohnCremona** [comment]
Thank you -- that looks very much simpler than I thought it would be.  I had also thought that the line "using namespace std;" only appeared in one place in a file (interface.h) which was included by just about every other file, but that turns out to be far from the truth.

Please make a PR and I will test.
