### ISSUE TITLE
Tests either take an awful long time or just never end on some arches

### ISSUE THREAD

**Issue by SnarkBoojum** [JohnCremona/eclib#63]
I have problems building the latest eclib on some arches: [see here](https://buildd.debian.org/status/package.php?p=eclib) ; for three of those failing, there is a clear error message stating the build was killed after 150min of inactivity ; I guess the fourth was killed likewise.

I tried to build eclib by hand on an armel box (a Debian porterbox - precisely available to debug things like this) and indeed after hours I see "Testing solve_conic..." displayed and nothing else.

Stopping the build and trying to run the tests separately, it looks like only solve_conic and solve_legendre get stuck like this.

Does that give you enough information to see what gets awry ? If not, what can I do to help pin down the issue ?

**Comment by SnarkBoojum** [comment]
Here is the difference in output when I stop the test for solve_legendre :
> --- out_ntl/solve_legendre.out  2019-09-09 14:00:15.000000000 +0000
+++ solve_legendre.testout      2020-01-08 09:26:13.022493835 +0000
@@ -416,201 +416,3 @@
 Disc(qz) = -13354814655463282827589091033876836
 Parametric solution is OK
 Enter coefficients a b c: 293911884200387681576093 106205605559 -687223946819
-Solution: (x:y:z) = (23840892990:133700736855785209:54824084629796371) --OK
-x = [-120543758034,-289421995022,431758255050] * [u^2,uv,v^2]
-y = [201353504898388438,-790335940111425618,-227587597953023497] * [u^2,uv,v^2]
-z = [111714818825405396,-86582800060098558,296193784378457843] * [u^2,uv,v^2]
-Disc(qx) = 291948141706231627067284
-Disc(qy) = 807933140308797241690526567735192668
-Disc(qz) = -124860358569955432897412098409203948
-Parametric solution is OK

**Comment by SnarkBoojum** [comment]
and if I run the test by hand, I see:
 
> (sid_armel-dchroot)jpuydt@abel:~/eclib-20190909/progs$ ./solve_legendre 
Solving ax^2 + by^2 + cz^2 = 0
Using method 4
Enter coefficients a b c: 293911884200387681576093 106205605559 -687223946819
293911884200387681576093 106205605559 -687223946819
  ***   Warning: not enough memory, new thread stack 500002816
  ***   Warning: not enough memory, new thread stack 250003456
  ***   Warning: not enough memory, new thread stack 125001728
  ***   Warning: not enough memory, new thread stack 500002816
  ***   Warning: not enough memory, new thread stack 250003456
  ***   Warning: not enough memory, new thread stack 125001728
  ***   Warning: not enough memory, new thread stack 62500864
  ***   Warning: not enough memory, new thread stack 31252480
  ***   Warning: not enough memory, new thread stack 15626240

**Comment by JohnCremona** [comment]
I won't have time to look into this until next week, but can make some preliminary comments.

First: you say the "build" is timing out but I guess that it is not actual build but the test runs (make check) which are?

Second: in both these cases there is an iteration and floating-oint arithmetic is used, so the possibility of rounding errors (machine dependent) causing an infinite loop is a potential cause.  If that is it a quick fix would be to make sure that such loops have a failsafe maximum number of iterations -- but I would not be able to test that myself.  When I do look into it I'll make a bugfix branch and hope you'll be able to test that.

**Comment by SnarkBoojum** [comment]
Indeed, building the Debian package means building and testing eclib, and it's the failing step.

If you have a patch, I can give it a try quite easily.

I'm now trying to run the inputs by hand to see which fail.

**Comment by SnarkBoojum** [comment]
For solve_legendre, the only failing input is the one quoted above -- and it's the only one giving "not enough memory" warnings

**Comment by SnarkBoojum** [comment]
For solve_conic, the failing tests are:
> 293911884200387681576093 0  106205605559  68722394681
206207486824798778186641 0 769034410087 80703111317

and they're also the same which trigger the warning.

**Comment by JohnCremona** [comment]
Thanks a lot -- that will certainly help debugging.

**Comment by JohnCremona** [comment]
Could you build the branch named 63 on your debugging machine?  Don't do a make check, just make and then run the two offending programs by
```
cd progs
./solve_conic < in/solve_conic.in > solve_conic.testout
```
and similarly with solve_legendre?  All this branch does is turn on some relevant debugging output, so if either is getting stuck in a loop and you kill each run almost immediately, the output file might help me see where the problem is.
Despite what I originally thought, there is almost no use of floating point in the reduction routines, but there is some.
I think I wrote this code in 1997!

**Comment by SnarkBoojum** [comment]
Hmmm... it gets stuck like before, and after killing it, when I look at the last log entry, there's nothing more than before (I also added 2>&1 to get the warnings in the log). For the other entries, there is more -- here it doesn't even say that it's starting to do anything : the series of warnings and that's all!

Since the problematic tests are the ones giving a series of pari warnings about having not enough memory : perhaps eclib exhibits the problem, but it really comes from pari ?

**Comment by JohnCremona** [comment]
That could be it. I *only* use pari for integer factorization. It is
initialized with some memory allocation and that can be increased by
setting an environment varable I think. Sorry but I am away from a computer
now.

**Comment by SnarkBoojum** [comment]
I dived into the code, adding "cout" everywhere : I tracked the problem down to the factor function in marith.cc (around line 470), and more precisely to the proof part: the call to is_prime(293911884200387681576093) is where eclib gets stuck.

So I checked if pari's gp can do the operation : it does! With a parisize of 4000000.

So I tried with just the simple change of this default parisize value in parifact.cc : it worked!

**Comment by SnarkBoojum** [comment]
Ok, I propose to fix this bug with : [pari_size.txt](https://github.com/JohnCremona/eclib/files/4039079/pari_size.txt)
but I still reported the issue against pari after I could reproduce the issue on a porterbox : [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=948475)

**Comment by JohnCremona** [comment]
That is very good. Thanks. I had already increased the value of PARISIZEMAX
for Sage after some rrports of failure.

Sorry that you had to take time over this.

**Comment by JohnCremona** [comment]
OK, so you found the place where the default PARI_SIZE is set.  There are actually two places in that file where it is set (in is_prime() and in factor()), which is bad since the default should be defined once in that file as a macro.
I do not want to reduce the default in the code.  The reason I increased it about a year ago was because the smaller value was causing problems with Sage users (in certain elliptic curve computations).  I think that users of the eclib package by itself (if there are any) can be expected to read the documentation and set environment variables, but not Sage users.  See doc/mwrank/mwrank.info lines ~240 for where this is mentioned.

**Comment by SnarkBoojum** [comment]
So what is the proper fix ?

**Comment by JohnCremona** [comment]
@SnarkBoojum Can you tell me if this is still an issue with the current version (tag 20210408)?

**Comment by SnarkBoojum** [comment]
Sorry, I lacked the time to have a look until now. It's now up to 20210415, so I'll try to package that for Debian, and in a few hours (days?) we'll see what the build servers will have to say.

**Comment by SnarkBoojum** [comment]
Well, it looks like there are still problems: [see the logs](https://buildd.debian.org/status/package.php?p=eclib&suite=experimental)

**Comment by JohnCremona** [comment]
> Well, it looks like there are still problems: [see the logs](https://buildd.debian.org/status/package.php?p=eclib&suite=experimental)

Sorry if I am missing something obvious, but I cannot see any logs at that link except for tthe tail of three, none of which show errors.  Can you post a  link to a log which shows a problem?

**Comment by SnarkBoojum** [comment]
If you click on 'Build-Attempted', it's a link to the full log.

**Comment by JohnCremona** [comment]
Thanks, I see the build logs now -- before I had clicked on "log" but that does not show the build log.

I can see no errors in the logs of te failing builds other than a timeout at the end.  When I run "make check" the last few lines are

m -rf nftmp
rm -rf snftmp
rm -rf tcurves
make[2]: Leaving directory '/home/jec/eclib/progs'
rm -f *.testout PRIMES 1
make[1]: Leaving directory '/home/jec/eclib/progs'
Making check in doc
make[1]: Entering directory '/home/jec/eclib/doc'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/jec/eclib/doc'
Making check in man
make[1]: Entering directory '/home/jec/eclib/man'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/jec/eclib/man'
make[1]: Entering directory '/home/jec/eclib'
make[1]: Nothing to be done for 'check-am'.
make[1]: Leaving directory '/home/jec/eclib'

where some temporary filies and directories in progs/ are removed, then "make check" is run in doc/ and man/ where there is nothing to do.

Does this help you diagnose the problem?  The timeout is occurring *after* all my tests have run successfully.

**Comment by SnarkBoojum** [comment]
On some architectures, after "rm -rf tcurves", make never announces it leaves eclib/progs : it just sits there. And after 5 minutes the build daemon decides something is amiss.

I checked : there are only 18 files in tcurves/, so it's definitely not the filesystem taking long deleting many small files...

I checked : if I run by hand, it gets stuck. And there is no progs/tcurve/ in sight, so rm should be finished. Running 'ps -ef' shows:

```
  jpuydt    6075  6074  0 09:11 pts/0    00:00:00 make check
  jpuydt    8035  6075  0 09:12 pts/0    00:00:00 make check_procs check_qcurves check_qrank check_g0n
  jpuydt    8040  8035  0 09:12 pts/0    00:00:00 /bin/bash -c for prog in solve_conic solve_legendre reduce_cubics list_cubics cubics; do echo "Testing ${prog}..."; ./${prog} < ./in/${prog}.in > ${prog}.testout 2>/dev/null && diff ${prog}.testout ./out_ntl /${prog}.out || exit $?; done
  jpuydt    8043  8040  0 09:12 pts/0    00:00:00 /home/jpuydt/eclib-20210415/progs/.libs/solve_conic
```

so solve_conic looks like it's still running.

**Comment by JohnCremona** [comment]
This is progress.  It makes sense, if the "make check" carries out checks in parallel, that some checks might not have finished even though the script appears to have reached the end.

I will look at the code behinf solve_conic and solve_legendre (which are two test programs for much of the same code) to see if there are any potentially infinite loops there which might depend in precision.  I will also see if I can tweak the "make check" script so that there is an indication in the log of when each test finishes, before it tests whether the expected and actual output differ.

**Comment by SnarkBoojum** [comment]
If you have a patch to make solve_conic more verbose, I can also apply it on the porterbox and report what gets printed.

**Comment by JohnCremona** [comment]
Thanks.  There are many  macros in the code which can be switched on, I am trying to work out which one(s) should be.  What would help would be to interrupt the running of solve_conic to see where in the code it is.  I would do that by running it in gdb, with the input from progs/in/solve_conic.in, and interrupt it manually.

Another helpful thing would be to hide the line "rm -f *.testout" and send the contents of solve_conic.testout when it times out, to see which example it is running, since the test input file has 65 examples in it.  But that might be misleading as the output is likely to be buffered.

**Comment by JohnCremona** [comment]
It would be overkill, but the output from a run of solve_conic (with the test input) after the following would be revealing:
libsrc/conic.cc  uncomment lines 28, 33 (so defining DEBUG_CONIC and DEBUG_REDUCE)
libsrc/legendre.cc, uncomment lines 30-34 (so defining DEBUG_MINV, DEBUG_LEM1, DEBUG_LEGENDRE and WATCH_REDUCTION).
As an alternative to patching the source code one could also configure with extra CFLAGS (-DDEBUG_CONIC and so on).

**Comment by SnarkBoojum** [comment]
Hmmm... libsrc/legendre.cc doesn't compile, but I modified lines 30-34 which makes 5 lines and you also listed DEBUG_MINV, DEBUG_LEM1, DEBUG_LEGENDRE and WATCH_REDUCTION, which makes 4 changes, so I'll use that now ;-)

**Comment by SnarkBoojum** [comment]
```
Testing thilbert...
11,18d10
< Starting to solve Legendre equation with coeffs 1234, -1, 5678
< Factor Base = [ 2 17 167 617 ]
< After gcd reduction, new coeffs are 617, -2, 2839
< scale factors are 1, 2, 1
< After squarefree reduction, new coeffs are 617, -2, 2839
< scale factors are 1, 2, 1
< Legendre equation with coeffs 617, -2, 2839 is not soluble!
< No certificate modulo a
```

**Comment by JohnCremona** [comment]
OK, I'm with you, and I'll try to work out what's happening.  Sorry not to have tested myself that the combination of switches I had suggested actually compiled.

**Comment by JohnCremona** [comment]
There's nothing wrong with the thilbert test, but with debugging turned on the outputis different (since I don't send debugging output to stderr as perhaps I should).  But I am running "make -k check" (with flag -k meaning "keep going")...

**Comment by JohnCremona** [comment]
The output from "make -k check_procs", after cd-ing to progs/, would be useful -- please?

**Comment by JohnCremona** [comment]
Meanwhile I have checked the logic behind the relevant code, in particular that the reduction loops should not ever loop forever: theoretically this is because at each pass through the loop some positive integer is strictly reduced.  There is no relevant floating point involvement here.  I do use a couple of macros to do rounded division of integers with control over whether one rounds up or down, and perhaps that could be platform-dependent.

**Comment by SnarkBoojum** [comment]
"make -k" won't save us here : "Testing solve_conic..." is stuck -- and doesn't print anything to tell us where.

**Comment by JohnCremona** [comment]
> "make -k" won't save us here : "Testing solve_conic..." is stuck -- and doesn't print anything to tell us where.

You mean that it is stuck with no output at all even with the debugging turned on?  It should at least output two header lines

> Solving ax^2 + bxz + cz^2 = dy^2
> Using method 4

before prompting for input.  Now, if there was no input then it would wait for ever.  So can you confirm that there is no output at all when running solve_conic < in/solve_conic.in, or show exactly what the output is?  Thanks

**Comment by SnarkBoojum** [comment]
Ah, no, it was with make check that nothing is printed ; if I run as you say, there's much more output, and it ends with:
```
Parametric solution:
x = [195924828285,2145280581885379595193169688,5872442016792135409459129921769285835917671]*[u^2,uv,v^2]
y = [57363880008362257,628106294443357445996190963797188,1719363809865435325426625130926352481483793500685]*[u^2,uv,v^2]
z = [61540493626424234,673838160952041003544277567799686,1844549175667748953847496454031950661610608575242]*[u^2,uv,v^2]
disc(qx) = 267238135737744073520404 = 4cd
disc(qz) = 36856041089473957501961224216840084 = 4ad
resultant(qx,qz)   = -2462334927856178605269320611019391015762951921790644768484 = d^2(b^2-4ac)
Parametric solution is correct!
Enter coefficients a b c d: 293911884200387681576093 0 106205605559 687223946819
  ***   Warning: not enough memory, new thread stack 500002816
  ***   Warning: not enough memory, new thread stack 250003456
  ***   Warning: not enough memory, new thread stack 125001728
  ***   Warning: not enough memory, new thread stack 500002816
  ***   Warning: not enough memory, new thread stack 250003456
  ***   Warning: not enough memory, new thread stack 125001728
  ***   Warning: not enough memory, new thread stack 62500864
  ***   Warning: not enough memory, new thread stack 31252480
  ***   Warning: not enough memory, new thread stack 15626240
```

which looks like a pari issue.

**Comment by JohnCremona** [comment]
OK, now I know what is happening.  Those are message from libpari, which are used to factor larger integers.

If I turn off all the previous debugging flags but instead turn one on in libsrc/parifact.cc then the output fro tha point on is


Enter coefficients a b c d: 293911884200387681576093 0 106205605559 687223946819
factor called with 687223946819
factor returns [687223946819]
is_prime called with 687223946819...and returns 1
factor called with 293911884200387681576093
factor returns [293911884200387681576093]
is_prime called with 293911884200387681576093...and returns 1
factor called with 106205605559
factor returns [106205605559]
is_prime called with 106205605559...and returns 1
Solution: (x:y:z) = (23840892990:54824084629796371:133700736855785209)

etc.    Now we have seen something like this before.  Because there are places where libpari fails when it has not enough memory, we have (in parifact.cc):
#define DEFAULT_PARI_SIZE 1000000000
which is obviously more than is needed to factor that 12-digit prime.  Is it possible that libpari itself is going into a loop, trying to get enough memory?  Do these test platforms have different amounts of memory?

A rather crude way to get around this would be to manually add the primes needed for these tests which is catered for by having a file called PRIMES in the progs/ directory with any useful primes listed, on per line.  It would be a pity to just remove these larger tests.

Does it work if you configure eclib, or just run the tests, with a smaller value of PARI_SIZE?  The code in parifact.cc will look for the envoronment variable PARI_SIZE when it initializes the pari system and use what is there if it is set, only using DEFAULT_PARI_SIZE if it is not.

**Comment by SnarkBoojum** [comment]
I removed a 0 in DEFAULT_PARI_SIZE, and things look better.

**Comment by JohnCremona** [comment]
OK -- I will update the release tarball with that change and a couple of others (very minor).

It is possible that this lower default PARI_SIZE will cause some trouble in Sage, but I'll update the Sage patch (trac #31443 will not be in the next release anyway, it seems, despite several bugs it fixes).

**Comment by SnarkBoojum** [comment]
Oh, there was still a problem, but I guess now we'll see the logs for the new version tomorrow morning.

**Comment by SnarkBoojum** [comment]
20210503 is perfect, closing.

Thanks!
