### ISSUE TITLE
20250225 ?!

### ISSUE THREAD

**Issue by SnarkBoojum** [JohnCremona/eclib#79]
I think that version is a mistake ; perhaps you could remove it and add another one?

**Comment by JohnCremona** [comment]
Sorry, the year was wrong. I'll fix it next week, travelling with no laptop now.

**Comment by JohnCremona** [comment]
When I added that tag I mistyped, it should have been 20240225.  Since then I have made quite a few code changes, mostly refactoring but also a bugfix.  I think the simplest thing to do now is to delete that tag, add a new one for today but also change the version to 20240408 to match the tag.  I will do that today.

**Comment by JohnCremona** [comment]
Done.

**Comment by tornaria** [comment]
@JohnCremona in the past you had release tarballs as in:
 - they are bootstrapped (i.e. autotools has been run)
 - they show up https://github.com/JohnCremona/eclib/releases with a filename `eclib-VERSION.tar.bz2`

This is the tarball I normally use to make the package for void linux. I'm just wondering if you will eventually do a release like that for 20240408 and/or future versions. Otherwise I'll adjust my template to use automatic tarballs.

No hurry at all, and no big deal, either way is fine (just that if you will go back to making release tarballs I'd prefer to use those).

**Comment by JohnCremona** [comment]
Yes certainly I will do this.  I had put a tag in but not made a release yet as I thought I might make some more changes, but I can do what you want, as before, later today.

**Comment by JohnCremona** [comment]
There's a new release now called 20240408 which I think I made in the same way as in the past.
